# Generated by Django 4.1.2 on 2022-10-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
    ]
