# Generated by Django 4.1.2 on 2022-10-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0002_alter_deals_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
