# Generated by Django 4.1.2 on 2022-11-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0002_reviews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='reviews/'),
        ),
    ]
