# Generated by Django 4.1.2 on 2023-03-08 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0003_orderplaced_is_assigned_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 21, 19, 53, 981408)),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
