# Generated by Django 4.1.2 on 2023-03-08 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0004_alter_coupon_valid_to_alter_orderplaced_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 21, 56, 54, 116292)),
        ),
    ]
