# Generated by Django 4.1.2 on 2022-10-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0004_customer_phone_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
