# Generated by Django 4.1.2 on 2022-11-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0005_alter_reviews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Pathanamthitta ', 'Pathanamthitta ')], max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Pathanamthitta ', 'Pathanamthitta ')], max_length=100),
        ),
    ]
