# Generated by Django 4.1.2 on 2022-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(max_length=200, null=True),
        ),
    ]
