# Generated by Django 4.1.2 on 2022-11-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0006_alter_customer_city_alter_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='star',
        ),
    ]
