# Generated by Django 4.1.2 on 2022-10-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
