# Generated by Django 4.1.2 on 2022-11-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0007_remove_reviews_image_remove_reviews_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
