# Generated by Django 4.1.2 on 2023-03-10 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0007_profile_latitude_profile_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 12, 30, 24, 910042)),
        ),
    ]
