# Generated by Django 4.1.2 on 2023-03-11 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0009_remove_orderplaced_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 29, 37, 452039)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='burger.product'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='order_number',
            field=models.IntegerField(default=1678539577),
        ),
    ]
