# Generated by Django 4.1.2 on 2023-03-11 14:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0010_alter_coupon_valid_to_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 20, 7, 53, 694842)),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
