# Generated by Django 4.1.2 on 2023-03-11 14:52

import burger.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0011_alter_coupon_valid_to_alter_orderplaced_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 20, 22, 40, 625808)),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='order_number',
            field=models.IntegerField(default=burger.models.generate_order_number, unique=True),
        ),
    ]
