# Generated by Django 4.1.2 on 2023-03-14 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0013_alter_coupon_valid_to_prebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdata',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burger.delivery_login'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 18, 29, 55, 784923)),
        ),
    ]
