# Generated by Django 4.1.2 on 2023-03-16 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0014_reviewdata_delivery_boy_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdata',
            name='sentiment_polarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 10, 13, 32, 21706)),
        ),
    ]
