# Generated by Django 4.1.2 on 2023-03-16 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0015_reviewdata_sentiment_polarity_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 10, 24, 50, 172546)),
        ),
    ]
