# Generated by Django 4.1.2 on 2023-03-16 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0016_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 10, 28, 36, 247988)),
        ),
        migrations.AlterField(
            model_name='reviewdata',
            name='sentiment_polarity',
            field=models.FloatField(default=0.0),
        ),
    ]
