# Generated by Django 4.1.2 on 2023-03-27 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0019_alter_coupon_valid_to_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 9, 42, 10, 958223)),
        ),
    ]
